In [3]:
import torch
torch.__version__

'1.12.1'

### Datatypes in Pytorch

In [4]:
# different data types in Pytorch
scalar = torch.tensor(2)
print(f'scalar.ndim: {scalar.ndim}')
print(f'scalar.shape: {scalar.shape}')

scalar.ndim: 0
scalar.shape: torch.Size([])


In [5]:
vector = torch.tensor([2, 3])
print(f'vector.ndim: {vector.ndim}')
print(f'vector.shape: {vector.shape}')

vector.ndim: 1
vector.shape: torch.Size([2])


In [6]:
MATRIX = torch.tensor([[2, 3],
                       [4, 5]]) # 2x2 matrix
print(f'MATRIX.ndim: {MATRIX.ndim}')
print(f'MATRIX.shape: {MATRIX.shape}')

MATRIX.ndim: 2
MATRIX.shape: torch.Size([2, 2])


In [7]:
TENSOR = torch.tensor([[[2, 3],
                        [4, 5]],
                       [[6, 7],
                        [8, 9]]]) # 2x2x2 tensor
print(f'TENSOR.ndim: {TENSOR.ndim}')
print(f'TENSOR.shape: {TENSOR.shape}')

TENSOR.ndim: 3
TENSOR.shape: torch.Size([2, 2, 2])


### Making Tensors

In [19]:
# Making random tensors
random_tensor = torch.rand(size=(2, 3,4))

print(f'random_tensor.ndim: {random_tensor.ndim}')
print(f'random_tensor.shape: {random_tensor.shape}')
print(f'random_tensor.dtype: {random_tensor.dtype}')    
print(random_tensor)

random_tensor.ndim: 3
random_tensor.shape: torch.Size([2, 3, 4])
random_tensor.dtype: torch.float32
tensor([[[0.4427, 0.7081, 0.8869, 0.8414],
         [0.6233, 0.4882, 0.8250, 0.4244],
         [0.7553, 0.6702, 0.9821, 0.0648]],

        [[0.2068, 0.7514, 0.5367, 0.4723],
         [0.8822, 0.2651, 0.6054, 0.5018],
         [0.7750, 0.7235, 0.2744, 0.6591]]])


In [20]:
# Making ones tensor
ones_tensor = torch.ones(size=(2, 3,4))
print(f'ones_tensor.ndim: {ones_tensor.ndim}')
print(f'ones_tensor.shape: {ones_tensor.shape}')
print(f'ones_tensor.dtype: {ones_tensor.dtype}')
print(ones_tensor)


ones_tensor.ndim: 3
ones_tensor.shape: torch.Size([2, 3, 4])
ones_tensor.dtype: torch.float32
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [15]:
# Making zeros tensor
zeros_tensor = torch.zeros(size=(2, 3,4))
print(f'zeros_tensor.ndim: {zeros_tensor.ndim}')
print(f'zeros_tensor.shape: {zeros_tensor.shape}')
print(zeros_tensor)


zeros_tensor.ndim: 3
zeros_tensor.shape: torch.Size([2, 3, 4])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [22]:
# Creating a range tensor
range_tensor = torch.arange(start=0, end=10, step=1)
print(range_tensor)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [37]:
# changing the shape of a tensor
range_tensor2 = torch.arange(0, 24, 1,).reshape(2, 3, 4)

print(f'range_tensor2.ndim: {range_tensor2.ndim}')
print(f'range_tensor2.shape: {range_tensor2.shape}')
print(f'range_tensor2.dtype: {range_tensor2.dtype}')
print(range_tensor2)

range_tensor2.ndim: 3
range_tensor2.shape: torch.Size([2, 3, 4])
range_tensor2.dtype: torch.int64
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [38]:
# changing the shape of a tensor
range_tensor3 = torch.arange(0, 24, 1, dtype=torch.float32).reshape(2, 3, 4)

print(f'range_tensor3.ndim: {range_tensor3.ndim}')
print(f'range_tensor3.shape: {range_tensor3.shape}')
print(f'range_tensor3.dtype: {range_tensor3.dtype}')
print(range_tensor3)

range_tensor3.ndim: 3
range_tensor3.shape: torch.Size([2, 3, 4])
range_tensor3.dtype: torch.float32
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])


In [45]:
# changing the device of a tensor
device = 'cuda' if torch.cuda.is_available() else 'cpu'
range_tensor4 = torch.arange(0, 24, 1, device=device).reshape(2, 3, 4)
print(f'device: {device}')
print(f'range_tensor4.ndim: {range_tensor4.ndim}')
print(f'range_tensor4.shape: {range_tensor4.shape}')
print(f'range_tensor4.dtype: {range_tensor4.dtype}')
print(range_tensor4)


device: cpu
range_tensor4.ndim: 3
range_tensor4.shape: torch.Size([2, 3, 4])
range_tensor4.dtype: torch.int64
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


### Tensors Basic Operations

In [54]:
# basic operations on Tensors
range_tensor5 = range_tensor4 - 3
# also: range_tensor5 = torch.sub(range_tensor4, 3)
print(f'range_tensor4:\n  {range_tensor4}')
print()
print(f'range_tensor5:\n  {range_tensor5}')


range_tensor4:
  tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

range_tensor5:
  tensor([[[-3, -2, -1,  0],
         [ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [17, 18, 19, 20]]])


In [55]:
range_tensor6 = range_tensor4 + 3
# also: range_tensor6 = torch.add(range_tensor4, 3)
print(f'range_tensor4:\n  {range_tensor4}')
print()
print(f'range_tensor6:\n  {range_tensor6}')


range_tensor4:
  tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

range_tensor6:
  tensor([[[ 3,  4,  5,  6],
         [ 7,  8,  9, 10],
         [11, 12, 13, 14]],

        [[15, 16, 17, 18],
         [19, 20, 21, 22],
         [23, 24, 25, 26]]])


In [56]:
range_tensor7 = range_tensor4 * 3
# also: range_tensor7 = torch.mul(range_tensor4, 3)
print(f'range_tensor4:\n  {range_tensor4}')
print()
print(f'range_tensor7:\n  {range_tensor7}')


range_tensor4:
  tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

range_tensor7:
  tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21],
         [24, 27, 30, 33]],

        [[36, 39, 42, 45],
         [48, 51, 54, 57],
         [60, 63, 66, 69]]])


In [57]:
range_tensor8 = range_tensor4 / 3
# also: range_tensor8 = torch.div(range_tensor4, 3)
print(f'range_tensor4:\n  {range_tensor4}')
print()
print(f'range_tensor8:\n  {range_tensor8}')


range_tensor4:
  tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

range_tensor8:
  tensor([[[0.0000, 0.3333, 0.6667, 1.0000],
         [1.3333, 1.6667, 2.0000, 2.3333],
         [2.6667, 3.0000, 3.3333, 3.6667]],

        [[4.0000, 4.3333, 4.6667, 5.0000],
         [5.3333, 5.6667, 6.0000, 6.3333],
         [6.6667, 7.0000, 7.3333, 7.6667]]])


In [59]:
# elemenet-wise multiplication
range_tensor9 = range_tensor4 * range_tensor4
# also: range_tensor9 = torch.mul(range_tensor4, range_tensor4)
print(f'range_tensor4:\n  {range_tensor4}')
print()
print(f'range_tensor9:\n  {range_tensor9}')


range_tensor4:
  tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

range_tensor9:
  tensor([[[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]],

        [[144, 169, 196, 225],
         [256, 289, 324, 361],
         [400, 441, 484, 529]]])


In [70]:
# matrix multiplication
range_tensor10 = torch.arange(0, 6).reshape(2, 3)
range_tensor11 = range_tensor10 @ range_tensor10.T
# also: range_tensor11 = torch.matmul(range_tensor10, range_tensor10.T)
print(f'range_tensor10 shape: {range_tensor10.shape}')
print(f'range_tensor10.T shape: {range_tensor10.T.shape}')
print(f'range_tensor11 shape: {range_tensor11.shape}')
print()
print(f'range_tensor10:\n  {range_tensor10}')
print()
print(f'range_tensor10.T:\n  {range_tensor10.T}')
print()
print(f'range_tensor11:\n  {range_tensor11}')


range_tensor10 shape: torch.Size([2, 3])
range_tensor10.T shape: torch.Size([3, 2])
range_tensor11 shape: torch.Size([2, 2])

range_tensor10:
  tensor([[0, 1, 2],
        [3, 4, 5]])

range_tensor10.T:
  tensor([[0, 3],
        [1, 4],
        [2, 5]])

range_tensor11:
  tensor([[ 5, 14],
        [14, 50]])


### Tensor Aggregation

In [84]:
print(f'range_tensor9:\n  {range_tensor9}')
print()
print(f'range_tensor9.sum():  {range_tensor9.sum()}')
print(f'range_tensor9.min():  {range_tensor9.min()}')
print(f'range_tensor9.max():  {range_tensor9.max()}')
print(f'range_tensor9.mean():  {range_tensor9.type(torch.float32).mean()}') # type casting to float32
print(f'range_tensor9.std():  {range_tensor9.type(torch.float32).std()}') # type casting to float32
print(f'range_tensor9.prod():  {range_tensor9.prod()}')
print(f'range_tensor9.argmax():  {range_tensor9.argmax()}')
print(f'range_tensor9.argmin():  {range_tensor9.argmin()}')


range_tensor9:
  tensor([[[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]],

        [[144, 169, 196, 225],
         [256, 289, 324, 361],
         [400, 441, 484, 529]]])

range_tensor9.sum():  4324
range_tensor9.min():  0
range_tensor9.max():  529
range_tensor9.mean():  180.1666717529297
range_tensor9.std():  168.39437866210938
range_tensor9.prod():  0
range_tensor9.argmax():  23
range_tensor9.argmin():  0


### Tensor Shape Manipulation